-- Schema setup for AcheAqui AI Customer Acquisition Platform

-- 1. Profiles (extends Supabase auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'admin',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Companies (The core entity, represents a business)
CREATE TABLE public.companies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  cnpj TEXT,
  category TEXT,
  address TEXT,
  city TEXT,
  state TEXT,
  phone TEXT,
  whatsapp TEXT,
  email TEXT,
  website TEXT,
  google_maps_url TEXT,
  google_rating NUMERIC(2,1),
  plan TEXT DEFAULT 'Free', -- Free, Pro, Premium
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. AI Data (Stores marketing materials generated by Gemini)
CREATE TABLE public.ai_data (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
  seo_description TEXT,
  seo_keywords TEXT[],
  instagram_post_ideas JSONB,
  faq_responses JSONB,
  generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Analytics (Mini CRM events)
CREATE TABLE public.analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL, -- 'profile_view', 'whatsapp_click', 'website_click'
  visitor_origin TEXT, -- Bairro/City of the visitor if known
  search_query TEXT, -- What the user searched to find them
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies (Draft)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics ENABLE ROW LEVEL SECURITY;

-- Profiles: Users can view and update their own profile
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Companies: Users can manage their own companies
CREATE POLICY "Users can view own companies" ON public.companies FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Users can insert own companies" ON public.companies FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Users can update own companies" ON public.companies FOR UPDATE USING (auth.uid() = owner_id);
-- (Public can view companies for search/directory)
CREATE POLICY "Public can view companies" ON public.companies FOR SELECT USING (true);

-- AI Data: Users can view and manage AI data for their companies
CREATE POLICY "Users can view own company ai_data" ON public.ai_data FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.companies WHERE companies.id = ai_data.company_id AND companies.owner_id = auth.uid())
);

-- Analytics: Users can view their own analytics
CREATE POLICY "Users can view own company analytics" ON public.analytics FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.companies WHERE companies.id = analytics.company_id AND companies.owner_id = auth.uid())
);
CREATE POLICY "Public can insert analytics" ON public.analytics FOR INSERT WITH CHECK (true);

-- Functions and Triggers
-- Automatically create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (new.id, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
